import './globals.css'
import { Inter } from 'next/font/google'
import styles from './layout.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Consumo API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.app}>
          <header className={styles.header}>
            <h1>Mi Aplicación</h1>
          </header>
          <div className={styles.container}>
            <nav className={styles.nav}>
              <ul className={styles.list}>
                <li className={styles.listItem}><Link href='/'>Carts</Link></li>
                <li className={styles.listItem}>Products</li>
                <li className={styles.listItem}><Link href='/carts/new'>New Carts</Link></li>
                <li className={styles.listItem}>New Products</li>
              </ul>
            </nav>
            <main className={styles.main}>
              {children}
            </main>
          </div>
          <footer className={styles.footer}>
            <p>Desarrollo: Jose Manuel 2023</p>
          </footer>
        </div>
      </body>
    </html>
  )
}
